export default {
  GENDER: {
    MALE: 'Male',
    FEMALE: 'Female'
  },

  STATES: [
    { id: 'AK', name: 'Alaska' },
    { id: 'AL', name: 'Alabama' },
    { id: 'AR', name: 'Arkansas' },
    { id: 'AZ', name: 'Arizona' },
    { id: 'CA', name: 'California' },
    { id: 'CO', name: 'Colorado' },
    { id: 'CT', name: 'Connecticut' },
    { id: 'DC', name: 'District of Columbia' },
    { id: 'DE', name: 'Delaware' },
    { id: 'FL', name: 'Florida' },
    { id: 'GA', name: 'Georgia' },
    { id: 'HI', name: 'Hawaii' },
    { id: 'IA', name: 'Iowa' },
    { id: 'ID', name: 'Idaho' },
    { id: 'IL', name: 'Illinois' },
    { id: 'IN', name: 'Indiana' },
    { id: 'KS', name: 'Kansas' },
    { id: 'KY', name: 'Kentucky' },
    { id: 'LA', name: 'Louisiana' },
    { id: 'MA', name: 'Massachusetts' },
    { id: 'MD', name: 'Maryland' },
    { id: 'ME', name: 'Maine' },
    { id: 'MI', name: 'Michigan' },
    { id: 'MN', name: 'Minnesota' },
    { id: 'MO', name: 'Missouri' },
    { id: 'MS', name: 'Mississippi' },
    { id: 'MT', name: 'Montana' },
    { id: 'NC', name: 'North Carolina' },
    { id: 'ND', name: 'North Dakota' },
    { id: 'NE', name: 'Nebraska' },
    { id: 'NH', name: 'New Hampshire' },
    { id: 'NJ', name: 'New Jersey' },
    { id: 'NM', name: 'New Mexico' },
    { id: 'NV', name: 'Nevada' },
    { id: 'NY', name: 'New York' },
    { id: 'OH', name: 'Ohio' },
    { id: 'OK', name: 'Oklahoma' },
    { id: 'OR', name: 'Oregon' },
    { id: 'PA', name: 'Pennsylvania' },
    { id: 'RI', name: 'Rhode Island' },
    { id: 'SC', name: 'South Carolina' },
    { id: 'SD', name: 'South Dakota' },
    { id: 'TN', name: 'Tennessee' },
    { id: 'TX', name: 'Texas' },
    { id: 'UT', name: 'Utah' },
    { id: 'VA', name: 'Virginia' },
    { id: 'VT', name: 'Vermont' },
    { id: 'WA', name: 'Washington' },
    { id: 'WI', name: 'Wisconsin' },
    { id: 'WV', name: 'West Virginia' },
    { id: 'WY', name: 'Wyoming' }
  ],

  TIME_ZONES: [
    { id: 'America/Adak', name: 'Adak' },
    { id: 'America/Anchorage', name: 'Anchorage' },
    { id: 'America/Boise', name: 'Boise' },
    { id: 'America/Chicago', name: 'Chicago' },
    { id: 'America/Denver', name: 'Denver' },
    { id: 'America/Detroit', name: 'Detroit' },
    { id: 'America/Indiana/Indianapolis', name: 'Indiana/Indianapolis' },
    { id: 'America/Indiana/Knox', name: 'Indiana/Knox' },
    { id: 'America/Indiana/Marengo', name: 'Indiana/Marengo' },
    { id: 'America/Indiana/Petersburg', name: 'Indiana/Petersburg' },
    { id: 'America/Indiana/Tell_City', name: 'Indiana/Tell_City' },
    { id: 'America/Indiana/Vevay', name: 'Indiana/Vevay' },
    { id: 'America/Indiana/Vincennes', name: 'Indiana/Vincennes' },
    { id: 'America/Indiana/Winamac', name: 'Indiana/Winamac' },
    { id: 'America/Juneau', name: 'Juneau' },
    { id: 'America/Kentucky/Louisville', name: 'Kentucky/Louisville' },
    { id: 'America/Kentucky/Monticello', name: 'Kentucky/Monticello' },
    { id: 'America/Los_Angeles', name: 'Los_Angeles' },
    { id: 'America/Menominee', name: 'Menominee' },
    { id: 'America/Metlakatla', name: 'Metlakatla' },
    { id: 'America/New_York', name: 'New_York' },
    { id: 'America/Nome', name: 'Nome' },
    { id: 'America/North_Dakota/Beulah', name: 'North_Dakota/Beulah' },
    { id: 'America/North_Dakota/Center', name: 'North_Dakota/Center' },
    { id: 'America/North_Dakota/New_Salem', name: 'North_Dakota/New_Salem' },
    { id: 'America/Phoenix', name: 'Phoenix' },
    { id: 'America/Sitka', name: 'Sitka' },
    { id: 'America/Yakutat', name: 'Yakutat' },
    { id: 'Pacific/Honolulu', name: 'Pacific/Honolulu' }
  ]
};
